pipeline {
    
    agent any

    environment {
        def myString = "Hello World"
        def myNumber = 10
        def myBoolean = true
    }

    stages{

        stage("Demo") {

            steps {

                echo "My string: ${myString}"
                echo "My Number: ${myNumber}"
                echo "My Boolean: ${myBoolean}"
            }


        }
    }
}